apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYzpzbG9nZTphZ2Z1cmRoZXMwMTE6cGFzc3dvcmQ6UDNPa05yR0hNUXh2djhLbEBjbHVzdGVyMC56MDJ1aS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=  # Ensure this is base64 encoded
